using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuessThatNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            // call the GuessThatNumber function
            GuessThatNumber();
            // prevent the console window from closing once GuessThatNumber ends
            Console.ReadKey();
        }

        static void GuessThatNumber()
        {
            // declare boolean values for our while loops, create an RNG, keep track of how many times
            // the player has guessed and keep track of the number that has been inputted by the player
            bool win = false;
            bool keepPlaying = true;
            Random rng = new Random();
            int guessCount = 0;
            string userInput = string.Empty;
            Console.WriteLine("GUESS THAT NUMBER!\n");
            // loop while keepPlaying is true
            while (keepPlaying == true)
            {
                // generate a random number
                int computerNumber = rng.Next(0, 101);
                // loop while win is false
                while (win == false)
                {
                    // ask the player to input a number from 1 to 100
                    Console.Write("Enter a number from 1 to 100: ");
                    // convert the string the player inputs into an int
                    int guess = int.Parse(Console.ReadLine());
                    // check if the guess is higher than the number generated by the RNG
                    // tell the player s/he guessed too high
                    if (guess > computerNumber)
                        Console.WriteLine("You're too high! Guess lower.");
                    // check if the guess is lower than the number generated by the RNG
                    // tell the player s/he guessed too low
                    else if (guess < computerNumber)
                        Console.WriteLine("You're too low! Guess higher.");
                    // check if the guess is equal to the number generated by the RNG
                    // tell the player s/he guessed correctly
                    else
                    {
                        Console.WriteLine("You've guessed the right number!");
                        // player wins
                        win = true;
                        // increment the guessCount
                        guessCount++;
                        // break out of the loop
                        break;
                    }
                    // check the absolute value of the difference between guess and computerNumber to
                    // guide the player to how close they are to guessing the number
                    if (Math.Abs(guess - computerNumber) <= 5)
                        Console.WriteLine("ON FIRE!!! You're really close to guessing the number!\n");
                    else if (Math.Abs(guess - computerNumber) <= 10)
                        Console.WriteLine("Hot.\n");
                    else if (Math.Abs(guess - computerNumber) <= 15)
                        Console.WriteLine("Warm.\n");
                    else if (Math.Abs(guess - computerNumber) <= 20)
                        Console.WriteLine("Cold.\n");
                    else
                        Console.WriteLine("Ice cold. You need to be a better guesser!\n");

                    // increment the guessCount
                    guessCount++;
                }  
                // output the result
                Console.WriteLine("\nIt took you {0} times to guess {1}.", guessCount, computerNumber);
                // reset the guessCount
                guessCount = 0;
                // ask the player if he or she would like to continue playing
                Console.Write("Would you like to keep playing? (Y/N): ");
                // take in the user input
                userInput = Console.ReadLine();
                Console.WriteLine();
                // check if the player inputted y/Y or n/N
                if (userInput == "Y" || userInput == "y")
                {
                    keepPlaying = true;
                    win = false;
                }
                else if (userInput == "N" || userInput == "n")
                    keepPlaying = false;
                else
                {
                    // have a little fun if the player inputs an invalid value :)
                    Console.WriteLine("We'll just quit because you fail at putting in a simple Y or N.");
                    keepPlaying = false;
                }
            }
            // thank the player for playing
            Console.WriteLine("Thanks for playing! Press any key to quit.");
        }
    }
}
